# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- '*'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
    checkLatest: true
- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'
- task: Yarn@3
  inputs:
    arguments: 'install'
- task: Yarn@3
  inputs:
   arguments: 'test'
- task: CmdLine@2
  inputs:
    script: 'VITE_API_KEY=$API_KEY && yarn build:prod'
  env:
    API_KEY: $(VITE_API_KEY)
- task: ArchiveFiles@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)/dist'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/weather-web-app.zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'